version: '3.9'
services:
  shim:
    build: .
    ports:
      - '1282:1282'
    volumes:
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./.env.dev
        target: /app/.env.dev
      - type: bind
        source: ./licenses
        target: /app/licenses
      - type: bind
        source: ./storage
        target: /app/storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
